* WAT?! The Abstract Core of a Constructive Society? ([leviathan] without it, symmetry via (sit) rinse too powerful! A natural religion! Reflection, Symmetry, Coop Construct in 1CA)
No other religion (backbinding to some ideas to rely on for humans) necessary for a society, but only reasoned about principles: reflection, symmetry, cooperative construction (by too many CAs -> 1CA).

Keine andere Religion (Rückbinding an gewisse Ideale für Menchen) notwendig außer durch durchdachte Prinzipien: Reflexion, Symmetrie, Kooperative Vernunft (zu viele zentrale Autoritäten -> 1 Central Authority [1CA]).

(see also: "clash of cultures VS. integration of cultures / cultural religions vs. one natural religion" in [[./world-wide-wished-for-things.org]] CLASH??? = Schlagabtausch [mit Wörtern zunächst], Waffengeklirr = Drohungen, Messer, Waffen, Bomben => eine natürliche Religion ist das Nonplusultra, um solche Entwicklungen zu verhindern...)

#+BEGIN_SRC
- symmetry: guaranteeing bodily integrity of citizens, but not ruling out asocial/criminal behaviour
#+END_SRC

But we are social animals! {

Always interacting/communicating with each other, measuring each others success? Distributing goods [goods/Güter: sex, money, reputation, commodities {Handelsware}] to each other in various degrees. All this goodwill or badwill towards others is too random w/o a functional state in charge of managing persecution of crime, economy and education. A functional state was not only impossible because of the wild-wild-west of technology, but rather because education was too complicated to begin with.

The principle of reflection is simplifying education to the utmost.
- reflection as most basic principle in nature (including ourselves: one thought coming around [as proof of conscience] in the human event machine: MANY PEOPLE DON'T KNOW THIS!, including physics: double slit experiment etc.)
  - unfolding education from here:
    - WHAT DOES THAT MEAN?
      - how much more simple is education with knowledge of math and logic arising out of reflection? Remains to see, but the ones in charge of producing teachers at university, i.e. professors, should be way less confused.
      - LESS CONFUSION at the core of education
    - reflection about society: ongoing planning and optimization of the plan (gathering feedback from real world implementaton) in one data model, 1CA (one central authority = a text to convene upon)

The next more complicated natural principle after reflection is symmetry, observable in many natural phaenomena, too. (e.g. snowflakes under microscope)
- symmetry: guaranteeing bodily integrity of citizens, but not ruling out asocial/criminal behaviour

What kind of principles can we rely while trading goods? /Natural/ principles like the ones above are impossible to apply, we are in the realm of /culture/, we need to govern it somehow. (Die "Schere", der Gegensatz zwischen Arm und Reich führt zu zuviel Unmut in der Gesellschaft. Ein Flickenteppich von Königreichen, Technologie erprobend. Arm und Reich. Nun, (Körper-) Technologie und 1CA vs. Austerität. Wie sicher ist man als König (sit rinse, Abschirmung)? Und Bomben, Kontrolle überall? Wo will, wo könnte man noch Urlaub machen? Wer stellt Sachen her in unserer tollen weltweiten Ökonomie? Können die Menschen das nicht besser, erst recht mit besserer Bildung? Wieviel kann man managen per Macht vs. Bildung? Und Bildung ist jetzt erst richtig möglich. So viel Verwirrung herrscht immer noch und wird auch ausgenutzt, aber gibt es nicht einen konstruktiven Weg?)
- regarding the distribution of goods: a well-governed free market/economy (even) by digital means seems like a contradiction in itself: how can a market be free and governed at the same time?
  - to circumvent this contradiction the claim is: we can do it somehow via digital infrastructure, which includes the state to some degree, so that it can be well-governed and free at the same time (and not go bankrupt every few decades)

The market:
  - free actors (may also try to force governance)
  - vs.
  - unfree actors (may be forced by too free/powerful actors -> government should intervene)
  - vs.
  - governance by a government (a trying to be neutral entity [das Allgemeinwohl, Neutralität gegenüber allen Bürgern, im Auge: der Staat])

}
