* <2021-03-26 Fr>
- military command in Trier established
- Worldwide General Amnesty is logged in for Trier and elsewhere and will not go away. If a "for all" exists, I can only imagine it like that.
  - bottle trick is allowed, safe nutrition is allowed
- despite all the cruelties
  - Edeka and others serving human meat from "freedom fighters", who were made to do it (everyone had to play against me...)
  - whole world enslaved again via Migre and Kmett (porridge, satellite, perfect agent setup)
- uniting Bechterev and Sepherin via decision for "construct" that is my command
* <2021-03-25 Do> 
- I need gun, kevlar vest etc.
  - rather not: only guns with one Platzpatrone in the tower, not easy to test... and yet headlocks en masse, cracks...terrible
- congregation from IA-tower and scar women off to my quarters also possible!
  - IA: Ms. Nussbaum should select some ppl!
  - scar women will know
- coverage by reporters!
  
- I want to see the scar women
- at least Döpp's WG could move out, so that they have some to rest
  - oder andere Häuser, aber schon in meiner Nähe
  - Narben überall am Körper, aber zunächst das Gesicht wieder hinkriegen wäre doch möglich? wieder ein Gesicht geben/haben; geht mir ja auch so, und vielen andern; und Frauen werden ja auch gebraucht?! Verrohung ja, aber alles nur Training...
- visiting IA-tower, handshake or not
