* my regulations regarding justice
- Mr. Trump? Mr. Obama? to see them I try soon
- Mr. Kmett needs better a katheter
- Pohl, Hannes? and others @ IAT (money -> wpn, kevlar??)??? write Email!
  - Mr. Pohl may move out of IAT and can take Kaysie's room if he likes!
  - Hannes as well, maybe another room is free?
  - Milan wants to learn with me
- Mr. Cleese should be alright
- too late for many others, piling up outside of IAT????!!!!
- too late for Ellie???? When I ate the brezels, it would have been the beginning of her end...
  - If Titus has to lie about this being a fact, it is true... sadly and if the play on me wasn't too smart...
  - Titus is asking to be out of play, away in safety and that should be allowed; how much more proof do I need, that Ellie is dead?
  - only an operation -- half an hour -- getting rid of her scar, could have saved her from drawing in the hospital, Mr. Trump had to have his chance; going to the hospital this night trying to save her, only a bullet for me (death traps whereever I go w/o sit scar rinse...)
- too late for Meduza?
- too late for Noam???? @ Nevada
- too late for Christiane???
- too late for Kajetan, no, Euthanasie en masse; to speak about it in the Realm, but not in real life (how to keep playing for me in neutrality -- but no neutrality for others locked up like me?)
  - one murder before KQ (see below Thomas), so prison 2 years!
- too late for Ms. Merten? yes???
- too late for David (Tellerficker), jmd rausgesucht, der eigentlich nicht gerne gegen mich spielt, Geschlossenheit demonstrieren, Max hat auch mal zugestochen...?????
  - but Max can be ok, gluten locks and money and survival (me already so strong!!!!)
- too late for Gebhardt @ Karlsruhe???
- too late for Ms. Nussbaum, hostage @ Trump?!
- too late for Steffi, hostage @ Ulf!!!!
  - one of the worst killers here in Trier, but it was allowed? whom did he kill?
- too late for Mr. Brooker, had to produce a propaganda movie inciting (gluten-locked or not) ppl to kill functionals (holocaust, genocide), envy and ridicule (gluten drawn bad faced)
  - escaping gluten lock seemed impossible
- prison for Marco and Goa-Marco 2 years (1 girl murdered), Döpp 3 (how many murders in Biewer?)
  - all these cushion fucker kills: only cushion fucks for both in prison
- Patrick May, prison, 2 years
- Ulf, also some prison
- Bernd, also some prison, maybe with Ulf (other prison than Trier)
- how is prison life for all of them??
- Bill, I want to test, he could have killed me long time ago in Marco's room (my former room)
- Thomas und sein Vater und sein Geld, Influenzer werden, ein bequemes Leben haben, Pöstchen
  - dass Krebs nur gemacht ist...
  - so viele Porridge-Opfer-Kills bzw. Gluten und im Schlaf langsam anziehen, Leute dafür geführt, Marcos Stimme
    - seit 2 Jahren, z.B. K, und 1000 EUR für jeden Kill, Konto der Eltern?!
    - Was soll mit dem Geld geschehen?
      - Warum bin ich noch am Leben? Nochmal Zahlungen...
    - Was halst man sich auf, wenn man mich aufnimmt?
      - bei 2 Mio. Versicherungsprämie: Inkriminierung oder mein Leben nehmen und ersteres ist passiert
        - w/o Mr. Trump someone could have paid me out?
          - unlikely? for rinsing had to be a secret! Anyway too many knew, and sold as freedom everywhere, but didn't really work against gluten locks
          - or: yes, this possibility did exist, but was not allowed...
          - but: all the attention me rinsing, healing my neck (3 years ago), surviving, working,
      - dann Phantasy-Play, Thinking-Hub, aber dabei so viele Leute reingeritten, d.h. tot, ausbezahlt oder vergessen gemacht
      - und jetzt ist tatsächlich das Gluten-Lock Geschichte
      - NUR DIESES "SPIEL" BOT FREIHEIT GENUG
  - Thomas: soll der sich alignieren und endlich bei seiner Mutter Mathe lernen dürfen, wie einst von ihr vorgeschlagen?
    - also sterben soll eigentlich keiner... keiner konnte wirklich vernünftig sein (Glutenlocks als Machtmittel (und die Macht wird halt genutzt) vs. "construct" -- beides jetzt gelöst, und das hat gedauert, v.a. ersteres)
      - that may even include Mr. Trump???
- also some prison, but different ones: Carsten Maschmeyer, Jan Böhmermann
  - +RIP+: Erdogan killed long ago? (let me align w/o gluten I...)
    - sein Geheimdienst bestochen (Wolfgang)???
  - Mr. Sarkozy should be free (let me align w/o gluten I...)
- Howard, should I fight against him? Cracking so many necks of pretty well aligned, but the real martial arts guys, which also became cruel against my followers (who was willingly my follower -- only some wise old men and women), and want their alignment back
  - soldiers kept me safe, willing to wait for my alignment

* <2021-03-29 Mo> Switch off satellites OR make devils Yay! (better the last)
- devils: porridge victims (commanded to play devils)
  - others? IAT Sepherin...
* <2021-03-29 Mo> Switch off satellites for mht communication over Germany!
- too much harassment
- calm finally
- all these devils...
