* <2021-03-25 Do> facts -- functionals vs. slaves
- Spielstadt Trier wegen mir: zu so vielen kann gesprochen werden, aber ist das wirklich gut? Warum geht das überhaupt?
  - yet, to have it a game...
  - ich als intercom host, andere Menschen wohl auch; @Militär: geht das nicht auch ohne Menschen?
- transfer of btc to german banks was stopped
- so many ppl have millions but cannot use it
- so much control is back, but to keep ppl under lock is the agenda
- hostage situation in IA-tower
- Kimmy/Ellie already died (I cried so much for me already, then they tell me she's waiting for at location X, and it's just a death trap or it's mixed, anyway dangerous, but could have died 2 days ago with gluten, today with mayo face, so what...)
- ia-tower:
  - so many devils (Heck, Gebhard, gluten brothers), plan to eliminate them (even Mr. Trump, Mr. Schulz)
  - Heck, Gebhard: many murders, but I want them to heal
  - KQ: crazy Wolfgang with guns and making gluten locks (also on Ellie, which was delivered to the game in IAT (some promised safety: no guns) by scar women, freeing her from this "Bruce" actor)
  - Lisa mit ein Kissenfickern geflohen
- terrible how freedom is endangered again and again
** body -> mind -> coop -> new society OR the same shit again never ending
- slavery is so much done, yes, why not...
- having Europe dwell again?!
- handshakes with ?
- these levels of alignment...
  - we want our stupid worker slaves
  - we want badly aligned sex
