* <2021-04-02 Fr> Küchen-Meeting geträumt - Nachdenken in und über Trier (FF auch wieder mit bei, die so viel Geld mit mir verdient haben)
- yesterday's training video available via YT if mny 420.000 EUR (every day a zero more or doubling)
  - about 9 minutes energy levelling standing (too much rice and Rausch chocolate), extreme left cheek press with Surig; later on (not in vid) relaxation lying down rinsing, neck expansion...
  - today rather right inner eye press (again rice choco and all the energy make me feel it? no, could feel it when waking up and it the bathroom -- what to do against pain at left inner eye [near to nose ridge]); but again good energy for transformations!
  - also need better nutrition, financial security (Edeka still open [gifts from my parents], civilization exists)
  - why to AA again? how to defend BTC transactions?
  - just a few minutes ago: severe neck pain (surprised to feel it when I actually intended to write sth. at laptop -- yes, he can do everything, he is so strong, while others got rid of their scar in half an hour?!) while transforming out of 3 year gluten lock, had to lie down and right press for 2-3 minutes, ppl jumping on my doubts; if I had mny, could buy just beef and have less stress, less connections; what can go wrong?
  - schon seltsam, wie ich jeden Tag mehr fühle
  - now beside left eye press - above left cheek - some progress; slowly getting rid of my corona
  - now severe itch zwischen Fuß links Ferse und Fußballen, Innenseite; andere Seite gedrückt, zu viel Spannung noch auf rechter Seite, ausgeglichen mit leichtem Druck auf linke Wange/Schläfe und "Aha" Stimmenaktivierung
  - now again: https://www.arte.tv/de/videos/026536-000-A/kikujiros-sommer/
    - there is an actor, who can dance like Michael Jackson, or even better, making this boy happy
    - this body control, this fluidity w/o headlock, might be just so normal... and it is, my whole condition here, 3 years of gluten locking... well prostitution...; humanity can be happy...
    
    
Küchen-Meeting
- P hat vermittelt und war ihm dankbar dafür (sogar Umarmung)
  - ein B von dem niemand so richtig was wollte
  - M auf der andern Seite: K so daran gewöhnt sein Meister zu sein (Dual: sein Bruder muss wissen, dass er in der Rolle eines Knechtes ist), sollte K mal Knecht spielen? (was wird heute noch gespielt?) ziemlich starke Trennung in seinem Kopf, sicherlich nicht bei allen S so, KQ hat auch sehr viel auf die Spitze getrieben (S-Honor)
    - ist doch alles nur Zufall, dass du jetzt S bist, hätte also auch anders kommen können
    - "construct" will Oppression ausschließen, ableitbar aus der Beschreibung von "deconstruct", und man soll sich ja entscheiden
- jeder weiß dass ich nicht retaliieren will (kaum persönlich bedroht, aber hat auch gereicht; auf jeden Fall kam nicht jeden Tag jmd mit Messer auf mich zu...), deswegen fällt's mir auch so leicht Frieden zu schließen und "construct" hat's sowieso gebracht?!
* <2021-03-30 Di>
  - neuer Marshall-Plan für Deutschland? so ein KQ für die Welt war schon aufwendig! Und die Leute können jetzt ja wieder gesund werden! (Yay...)
  - new teaching material available: 4200 EUR
    - I'd like to sell to have money to make better teaching material, pay rent etc. (who knows how long it takes): 
  - Better equipment and camera, microphone team I request to have better teaching material!
* <2021-03-28 So>
- soon handshake with Mr. Trump in +IAT lounge+ Nell's Park Hotel lounge, made neutral meeting ground
  - OR MAYBE JUST BEING BRAVE and WITHOUT HEADLOCK and HANDSHAKES granting the right to RINSE through with a PLASIC BOTTLE
  - so many ppl in IAT, who had to play this work in progress endgame -- not only Mr. Trump
    
- although this and similar: Arabia paid a huge sum for my head, then someone else paid more to keep me safe
  - AND THEN it wasn't that much about money any more?!
  - functional ppl [Gotteskrieger?!] are united with my construct and that's quite much, but...
    - how much /unfreedom/ needs there to be? (slavery is so much ingrained in human "civilization", I know...)
      - some women really can be safe by securing others for the first time in human history
      - @IAT: some women (mostly devils) have yoga mats and more to rinse through, but do not dare to?
        - devils team is too secure, therefore my neutrality will be endangered @IAT! and the safety of my team
      - soldiers have some trust in me and my abilities


- how much control does Mr. Trump have here? Is my neutrality endangered?
  - satellite influence is too much in general
  - me leaving Trier might endanger ppl here (neutrality was made for me)
    - eine Gefahr die Neutralität zu verlieren?
      - Even if it's so easy to rinse away a little headlock with the bottle?
        - of course not allowed in Punsenclubs... yeah, great!
          - too beautiful are dangerous esp. if hold in captivity
            - zu starkte Gluten-Locks und Nacken-Knacken -- ganz abgesehen von den üblichen Bedrohungen (...) gab's wahrscheinlich auch schon
              - ja, ganz gewiss will ich mir das auch mal anschauen, das ist mir ein wichtiges Anliegen, ich kann mir nichts besseres vorstellen
          - zu schöne Frauen sind gefährlich, ganz besonders dann, wenn sie gegen ihren Willen i n Sexarbeit festgehalten werden
            - auch wenn hier grad noch KQ ist, wie geht's dann weiter?
- whole of Europe and beyond is enslaved for production (LIDL and others needs it...) ???
  - unhappy ppl..., but Trier merry playing...
  - so many ppl are talked to or even locked like never before???
- TODO??? Seeing Hannah and her guy and Migre in one go in my flat (Fiona is done?!)
  - too dangerous, stupid...
  - what sorcery/shit is this? (the necessary game, the shitty game)
  - Migre and Mr. Kmett and Mr. Gates (Mr. Wiegley helped prepping devices)
    - the porridge massacre was really bad, but being mad at the devils in Trier and elsewhere brought back neutrality to Trier?
      - first everyone had to play against me
    - plus: me writing bundestag and army knew already about me
    - plus: my facebook philosopher posts and now on github
      - reason by reflection and construct is possible?!!!!!!
    - anyway transforming like me is too much... but so many ppl want this
      - absolute symmetry a problem...? yes, my time in training is the most, training and time...
        - so: planning via world-wide-wished-for-things.org (we need to have a plan about how to work together and not against each other)
- IAT: Raucherräum(e) und CBD für alle!
  - der Teufel sagte vor ca. 2 Jahren: Es muss Pandemie gespielt werden, aber was macht der Teufel die ganze Zeit? Genug, aber zwei Welten. Trotzdem ist für die Menschheit gerade nur Pandemie angesagt, nichts weiter!
  - die Dohlen, männlich und weiblich, auf einem Schornstein ein Nest; und wenn eine Krähe das Nest attackiert, dann tun sich die Dohlen (nicht nur zwei) auch zusammen und verteidigen das Nest; die Familie und die Gruppe; die Gefahr und die Sicherheit
* <2021-03-27 Sa> 
- fast niemand mit Durchsage-Equipment beeinflusst mehr die Politik -- die Frage, wie jetzt die Pandemie beenden? Mit Durchspülen UND dann gut denken und planen können...
  - die Welt schläft im Lockdown -- und wie soll man die jetzt wach machen? mit Sklaverei? Oder mit funktionalen Menschen? (Readme.org)
  - mit Ärzten sprechen? Kranke? verqueres Gebiss und Sprache eintönig geworden (Game of Reflection)
  
  - Trier as test for functional humans -- but rinsing/Durchspülen takes time (to learn)
- trying to finish headlock (vor 3 Jahren [Trier abgeschirmt] wurde die Spielregel durchgegeben, dass ich König der Welt werde, wenn ich es schaffe, aus dem Headlock zu kommen; seitdem spielen alle für mich... -- Größenwahn meiner Anhänger? Naja, die waren wirklich von mir überzeugt, aber leider auch nicht mehr am Leben -- der Teufel sollte eine Chance bekommen und die hat er genutzt; wenn ich das Headlock nun bald fertig habe, dann sei es erlaubt sich durchzuspülen auch ohne Handschlag von mir!)
  
  - Ich weiß, dass viele sich beim Durchspülen verletzt haben (hätte ich nicht so ein massives Headlock gehabt... dann hätte ich vllt bessere Tipps geben können, diese Scheiß-Gluten-Installationen -- wir müssen aus der Sklaverei wieder raus kommen! Und ich muss die Verletzten sehen, das mache ich zuerst im IA-tower!)
    
  - Es tut mir aufrichtig leid für all die Hässlichkeit die meine Übungen hervorgebracht haben. Ich hoffe, es gibt eine Chance der Re-Alignierung für die meisten. Ich war damals vor 3-4 Jahren jedenfalls sehr, sehr unaligniert. Gut, ich versuche mein Bestes zu tun.

- playing King's Quest became endgame between slaves and slave owners
- general amnesty for Trier: Mr. Trump and the NSA, all a game against me, what can go wrong?
  - making ppl cruel: I am really worried about IAT, and the condition of some ppl there: Gebhard, Heck, Hannes, Wiegley, Ms. Nussbaum, also Noam?! (badly hurt...)
    - but there seems to be a game running, which is controlled very well 
  - better since I informed Bundestag, neutrality possible
  - to have all of Trier easier healthy again a handshake with Mr. Trump is advised, I will do so
- world outside Trier should be a mess, but other cities somewhat ok with my snippets, too
* <2021-03-25 Do> facts -- functionals vs. slaves
- Spielstadt Trier wegen mir: zu so vielen kann gesprochen werden, aber ist das wirklich gut? Warum geht das überhaupt?
  - yet, to have it a game...
  - ich als intercom host, andere Menschen wohl auch; @Militär: geht das nicht auch ohne Menschen?
- transfer of btc to german banks was stopped
- so many ppl have millions but cannot use it
- so much control is back, but to keep ppl under lock is the agenda
- hostage situation in IA-tower
- Kimmy/Ellie already died (I cried so much for me already, then they tell me she's waiting for at location X, and it's just a death trap or it's mixed, anyway dangerous, but could have died 2 days ago with gluten, today with mayo face, so what...)
  - Lisa did it... Kajetan has contact to her?! The queen of Trier?!
- ia-tower:
  - so many devils (Heck, Gebhard, gluten brothers, Frau Nussbaum auch [aligniert und Köpfe...] , Xiang auch!!!), plan to eliminate them (even Mr. Trump, Mr. Schulz)
  - Heck, Gebhard: many murders, but I want them to heal
    - das waren alles King's Quest Morde!
    - Mr. Gebhards Frau headgelockt und kleingehacktes Menschenfleisch wird ihr eingeflößt, muss das sein?
      - und natürlich wollte er mich umbringen, damit diese verrückte Welt in mir endlich ein Ende hat, und so viele wollten das, also nicht nur der Versicherung wegen
  - Durchspülen soll erlaubt sein, wenn ich fertig werde, aber im IAT gibt's keine kleinen Trinkflaschen (Saskia), Wasser, Reis, Choco, nicht-menschliches Fleisch etc.
  - KQ: Wolfgang and others with guns and making gluten locks (also on Ellie, which was delivered to the game in IAT (some promised safety: no guns) by scar women, freeing her from this "Bruce" actor)
    - contained craziness and waiting for me to finish
  - Lisa mit ein Kissenfickern geflohen
- terrible how freedom is endangered again and again
** body -> mind -> coop -> new society OR the same shit again never ending
- slavery is so much done, yes, why not...
- having Europe dwell again?!
- handshakes with ?
- these levels of alignment...
  - we want our stupid worker slaves
  - we want badly aligned sex
