* <2021-03-27 Sa> 
- trying to finish headlock
- playing King's Quest became endgame between slaves and slave owners
- general amnesty for Trier: Mr. Trump and the NSA, all a game against me, what can go wrong?
  - making ppl cruel: I am really worried about IAT, and the condition of some ppl there: Gebhard, Heck, Hannes, Wiegley, Ms. Nussbaum, also Noam?! (badly hurt...)
    - but there seems to be a game running, which is controlled very well! 
  - better since I informed Bundestag, neutrality possible
  - to have all of Trier easier healthy again a handshake with Mr. Trump is advised, I will do so
- world outside Trier should be a mess, but other cities somewhat ok with my snippets, too
* <2021-03-25 Do> facts -- functionals vs. slaves
- Spielstadt Trier wegen mir: zu so vielen kann gesprochen werden, aber ist das wirklich gut? Warum geht das überhaupt?
  - yet, to have it a game...
  - ich als intercom host, andere Menschen wohl auch; @Militär: geht das nicht auch ohne Menschen?
- transfer of btc to german banks was stopped
- so many ppl have millions but cannot use it
- so much control is back, but to keep ppl under lock is the agenda
- hostage situation in IA-tower
- Kimmy/Ellie already died (I cried so much for me already, then they tell me she's waiting for at location X, and it's just a death trap or it's mixed, anyway dangerous, but could have died 2 days ago with gluten, today with mayo face, so what...)
  - Lisa did it... Kajetan has contact to her?! The queen of Trier?!
- ia-tower:
  - so many devils (Heck, Gebhard, gluten brothers, Frau Nussbaum auch [aligniert und Köpfe...] , Xiang auch!!!), plan to eliminate them (even Mr. Trump, Mr. Schulz)
  - Heck, Gebhard: many murders, but I want them to heal
    - das waren alles King's Quest Morde!
    - Mr. Gebhards Frau headgelockt und kleingehacktes Menschenfleisch wird ihr eingeflößt, muss das sein?
      - und natürlich wollte er mich umbringen, damit diese verrückte Welt in mir endlich ein Ende hat, und so viele wollten das, also nicht nur der Versicherung wegen
  - Durchspülen soll erlaubt sein, wenn ich fertig werde, aber im IAT gibt's keine kleinen Trinkflaschen (Saskia), Wasser, Reis, Choco, nicht-menschliches Fleisch etc.
  - KQ: Wolfgang and others with guns and making gluten locks (also on Ellie, which was delivered to the game in IAT (some promised safety: no guns) by scar women, freeing her from this "Bruce" actor)
    - contained craziness and waiting for me to finish
  - Lisa mit ein Kissenfickern geflohen
- terrible how freedom is endangered again and again
** body -> mind -> coop -> new society OR the same shit again never ending
- slavery is so much done, yes, why not...
- having Europe dwell again?!
- handshakes with ?
- these levels of alignment...
  - we want our stupid worker slaves
  - we want badly aligned sex
