* <2021-03-28 So>
- how much control does Mr. Trump have here? Is my neutrality endangered?
  - satellite influence is too much in general
  - me leaving Trier might endanger ppl here (neutrality was made for me)
    - eine Gefahr die Neutralität zu verlieren?
      - Even if it's so easy to rinse away a little headlock with the bottle?
- whole of Europe and beyond is enslaved for production (LIDL and others needs it...) ???
  - unhappy ppl..., but Trier merry playing...
  - so many ppl are talked to or even locked like never before???
- TODO Seeing Hannah and her guy and Migre in one go in my flat (Fiona is done?!)
  - what sorcery/shit is this? (the necessary game, the shitty game)
  - Migre and Mr. Kmett and Mr. Gates (Mr. Wiegley helped prepping devices)
    - the porridge massacre was really bad, but being mad at the devils in Trier and elsewhere brought back neutrality to Trier?
      - first everyone had to play against me
    - plus: me writing bundestag and army knew already about me
    - plus: my facebook philosopher posts and now on github
      - reason by reflection and construct is possible?!!!!!!
    - anyway transforming like me is too much... but so many ppl want this
      - absolute symmetry a problem... yes, my time in training is the most, training and time...
        - so: planning via world-wide-wished-for-things.org (we need to have a plan about how to work together and not against each other)
- IAT: Raucherräum(e) und CBD für alle!
  - der Teufel sagte vor ca. 2 Jahren: Es muss Pandemie gespielt werden, aber was macht der Teufel die ganze Zeit? Genug, aber zwei Welten. Trotzdem ist für die Menschheit gerade nur Pandemie angesagt, nichts weiter!
  - die Dohlen, männlich und weiblich, auf einem Schornstein ein Nest; und wenn eine Krähe das Nest attackiert, dann tun sich die Dohlen (nicht nur zwei) auch zusammen und verteidigen das Nest; die Familie und die Gruppe; die Gefahr und die Sicherheit
* <2021-03-27 Sa> 
- fast niemand mit Durchsage-Equipment beeinflusst mehr die Politik -- die Frage, wie jetzt die Pandemie beenden? Mit Durchspülen UND dann gut denken und planen können...
  - die Welt schläft im Lockdown -- und wie soll man die jetzt wach machen? mit Sklaverei? Oder mit funktionalen Menschen? (Readme.org)
  - mit Ärzten sprechen? Kranke? verqueres Gebiss und Sprache eintönig geworden (Game of Reflection)
  
  - Trier as test for functional humans -- but rinsing/Durchspülen takes time (to learn)
- trying to finish headlock (vor 3 Jahren [Trier abgeschirmt] wurde die Spielregel durchgegeben, dass ich König der Welt werde, wenn ich es schaffe, aus dem Headlock zu kommen; seitdem spielen alle für mich... -- Größenwahn meiner Anhänger? Naja, die waren wirklich von mir überzeugt, aber leider auch nicht mehr am Leben -- der Teufel sollte eine Chance bekommen und die hat er genutzt; wenn ich das Headlock nun bald fertig habe, dann sei es erlaubt sich durchzuspülen auch ohne Handschlag von mir!)
  
  - Ich weiß, dass viele sich beim Durchspülen verletzt haben (hätte ich nicht so ein massives Headlock gehabt... dann hätte ich vllt bessere Tipps geben können, diese Scheiß-Gluten-Installationen -- wir müssen aus der Sklaverei wieder raus kommen! Und ich muss die Verletzten sehen, das mache ich zuerst im IA-tower!)
    
  - Es tut mir aufrichtig leid für all die Hässlichkeit die meine Übungen hervorgebracht haben. Ich hoffe, es gibt eine Chance der Re-Alignierung für die meisten. Ich war damals vor 3-4 Jahren jedenfalls sehr, sehr unaligniert. Gut, ich versuche mein Bestes zu tun.

- playing King's Quest became endgame between slaves and slave owners
- general amnesty for Trier: Mr. Trump and the NSA, all a game against me, what can go wrong?
  - making ppl cruel: I am really worried about IAT, and the condition of some ppl there: Gebhard, Heck, Hannes, Wiegley, Ms. Nussbaum, also Noam?! (badly hurt...)
    - but there seems to be a game running, which is controlled very well 
  - better since I informed Bundestag, neutrality possible
  - to have all of Trier easier healthy again a handshake with Mr. Trump is advised, I will do so
- world outside Trier should be a mess, but other cities somewhat ok with my snippets, too
* <2021-03-25 Do> facts -- functionals vs. slaves
- Spielstadt Trier wegen mir: zu so vielen kann gesprochen werden, aber ist das wirklich gut? Warum geht das überhaupt?
  - yet, to have it a game...
  - ich als intercom host, andere Menschen wohl auch; @Militär: geht das nicht auch ohne Menschen?
- transfer of btc to german banks was stopped
- so many ppl have millions but cannot use it
- so much control is back, but to keep ppl under lock is the agenda
- hostage situation in IA-tower
- Kimmy/Ellie already died (I cried so much for me already, then they tell me she's waiting for at location X, and it's just a death trap or it's mixed, anyway dangerous, but could have died 2 days ago with gluten, today with mayo face, so what...)
  - Lisa did it... Kajetan has contact to her?! The queen of Trier?!
- ia-tower:
  - so many devils (Heck, Gebhard, gluten brothers, Frau Nussbaum auch [aligniert und Köpfe...] , Xiang auch!!!), plan to eliminate them (even Mr. Trump, Mr. Schulz)
  - Heck, Gebhard: many murders, but I want them to heal
    - das waren alles King's Quest Morde!
    - Mr. Gebhards Frau headgelockt und kleingehacktes Menschenfleisch wird ihr eingeflößt, muss das sein?
      - und natürlich wollte er mich umbringen, damit diese verrückte Welt in mir endlich ein Ende hat, und so viele wollten das, also nicht nur der Versicherung wegen
  - Durchspülen soll erlaubt sein, wenn ich fertig werde, aber im IAT gibt's keine kleinen Trinkflaschen (Saskia), Wasser, Reis, Choco, nicht-menschliches Fleisch etc.
  - KQ: Wolfgang and others with guns and making gluten locks (also on Ellie, which was delivered to the game in IAT (some promised safety: no guns) by scar women, freeing her from this "Bruce" actor)
    - contained craziness and waiting for me to finish
  - Lisa mit ein Kissenfickern geflohen
- terrible how freedom is endangered again and again
** body -> mind -> coop -> new society OR the same shit again never ending
- slavery is so much done, yes, why not...
- having Europe dwell again?!
- handshakes with ?
- these levels of alignment...
  - we want our stupid worker slaves
  - we want badly aligned sex
