#+Title: Ursächliche Notiz aus der Reflexionskammer (die Meinungen der Welt -- ein Gefängnis für mich; naja, Shenti #1)
#+Author: René Tobner
* Safety
Sicher sein (auch mit magic hat) Nur Fleisch, keine Carbs (nichtmal Pfeffer)
Need magic hat to inspect ppl!!!!! (can find out about anyone's state of mind!!!!)

* Teufel, die Enspiele spielen, immer noch [denk' es dir so René]
What about Noam and Martha? How stupid am I about their safety?

Wer war der Maldei-Schauspieler und dieses Playing Safe about Christiane? Köpfe rollen lassen;
Ob ich das hier sicher kann, und so viele andere Menschen werden gefährdet...
Nur noch Fleisch, aufpassen mit nicht Bio-Zitrone.
Saar 48...
Es könnte wohl nicht mehr so sein, dass SklavInnen existieren. Und ich soll alle retten?!
Nicht angemeldete Prostitution in Saar 48? Oder generell in Deutschland?
Ordnungskräfte vs. Magic Hat Wonderland // Nur sind wohl genügend Ordnungskräfte schon wieder Einsatz bereit?
Meine Werder-Mischpoke
Biewer (Peter, Vito)
Ganz Trier -- alle wollen schön weiterspielen
Von Herrn Trump gut korrumpiert. Reichsphilosophie -- Succumbing.
Playing Safe about Lisa? Von wegen bei Herrn Trauth?
Playing Safe generell? Wie stark ist der Teufel in Deutschland noch? Wieviele Leute können sich durchspülen?
Deutschland das Land der Dichter und Denker? Und wieviele können noch denken? Scheiß-Locks und kein Training...
Marco wirklich als Philosoph repräsentiert in den großen Tageszeitungen? Und dann ausgelöscht, dass er nicht wirklich als solcher erkannt wurde -- niemand hat das geglaubt. Dann andere: Ulf hätte das Rennen machen sollen...

Nukes on USA? bunker survive life?

Media coverage on "marriage" simulation ready? A real screen wipe!
- pretty much unrelatable w/o speaking about communication in Realms (foreign thinking evoking my words)
  - bringing forth this other world in me: many realms in, ppl and their phantasy (using my phantasy -- my visual images), a game of reflection to bring me down, slander (BILD-Zeitung, musings about what is allowed regarding sex; turning the world upside down via cushion condom sex)

Alles nur ein Spiel für mich (aber: Porridge-Horror!). We made it so. Mr. Trump out of the loop quite some time already.
Ich musste lernen, wie ich sicher bin. Wieviele Tipps brauche ich? Meine Ressourcen?

Need magic hat to inspect ppl!!!!!

Die ganze Welt schaut sich jetzt meine Texte an und eigentlich kann jeder wieder vernünftig sein?! (Jede Nach eine neue Welt -- und wenn alles von Trier aus in die Welt gesendet wird und alle daran interessiert sind, dann funktionale Menschen, funktionaler Staat (Staat: Infrastrukturverbesserungen: Auto, Bahn, Flugverkehr, Kommunikation; Gesundheit, psychisch und sozial können wir komplett abhaken?!) Kann man da jetzt schon nen Smiley machen? Wahrscheinlich schon! :-) (Das Lernen und das Rinsen...?!)
Bloß nicht vergessen, wieviele Frauen und Kissenficker ihr Leben lassen mussten. Das Thema Sex und Liebe, was kann da schon schief gehen???? Kiss-AND-Fuck, sex drive control...
Das Spiel bei mir und die Verrücktheit -- und jetzt rinsen so viele...
Das Spiel bei mir und die Verrücktheit -- but it had to be done just like so (thinking, phantasy, reflection game)
gn8!
* Pardoning VS Retaliating
  There seems to be nothing to condone, so many ppl died for me already.
Jörg und Sascha.. OK!
Miss Monique OK!
Meduza OK!
Christiane OK!
Shannon Trump: OK!
"Jan" and Meicol: talk.
Jan Hess: OK!

whole Kompze: OK!
(even Mr. Kreller? [knew about rinsing, too])
Migre and Debo,
all of R19 and some more? (I want to see them happy and reasonable again? I want it, but...)
All of Trier! OK!

VS

KILLINGS OF:

Pinocchio Wein
Porridge
Cushion Fuckers
Bernd und Steffi safe and w/o guilt (attempts to kill and eat Freya: but nothing really happened)

So unklar:
dass ich der Ursprung bin für die Anfeindungen anderer,

meistens nur bespielt von Trier und Koblenz, (bis meine Familie und Freunde mir Zuspruch bringen durften; warum mussten alle gegen mich sein? Um die Sklaverei zu retten. Durchspülen verboten.)

mit meinem Wissen über Körper und Geist verblendet,
sollte ich als Kissenficker von Trier sterben.
All meine geistigen Errungenschaft und dementsprechenden Ehrungen jmd anders zuteil.
Noch eine Runde Sklaverei für die Menschheit.
Ressourcenknappheit: Fleisch?! Wer darf Fleisch haben?
Luzifer Erwachen mit Kaffee und Frankfurter Rindswürstchen: so viele Nacken geknackt, von wegen ohnmächtig.
Just a Guessing Game: How to be safe under influence, under slavery.
at first Germany (test case) and ever more ppl on the world. Haha.

Die halbe Welt sollte meinen Porridge essen (sogar mit Gluten) und sterben UND jetzt wird Retaliation gefordert!

id = opinions on me safety/unsafety for some masters want their slaves; Hochkultur impossible in slavery, everyone needs to be functional...

Verbalizing HELPS while RINSING: "this safety/unsafety of mine" while rinsing: the reflection of the ultimate risk of the Realm. Focus on what while endangered in your own event machine?
thinking my identity via ID, the identity function, or THIS, the current object
  really helpful to conquer my thinking again!

* Startgame: How to?
  Startgame: Euanthropie [mit: shenti #1]
  VS.
  Endgame-Szenarios: Misanthropie [mit: war, slavery etc.]
  
* Liebe und Mitmenschlichkeit?
  Mit einem Menschen sein wollen/können? Erwartungen über Konstruktionsmöglichkeiten der Gesellschaft klären: die Koinzidenz (100 Jahre Krieg und Frieden in meinem Kopf) -- jede Nacht eine neue Welt. So schwierig für die Menschen und die Welt. Wettentspannen, Wettverspannen. Optimum über das Denken/Kommunikation als Ideal vorhanden. Einbindung in die Welt (jeder Mensch, jede Nation) möglich, aber schwierig. Und Menschen wollen noch spielen/denken mit mir...
  Wahres Endgame per Shenti #1 (own health/body at core). What's the new game? Startgame, construct, yaddayadda...
  
* Ursachen vs. gute Gründe:
  
  Ursachen/Prinzipien:
  
  Symmetry u. Reflexion, gut für Körper und Geist respektive
  
  body at core; gesunder Körper in absoluter Symmetrie (rinsing!) ist Voraussetzung für:
  
  absolutes Reflexionspotential
  
  Worüber überhaupt nachdenken/reflektieren?
  
  Reflexion über (um vernünftig zu bleiben in Gesellschaft): Konstruktion vs. Dekonstruktion
  Konstruktion als abstraktes Konzept der gute Grund schlechthin. Treibt gut und schlecht auf die Spitze...
  
  VERLASSEN AUF: Konstruktionsmöglichkeiten der Gesellschaft mit gegenwärtiger Technologie
  Körpertechnologie: Absolute Alignierung
  Gesellschaftstechnologie: smart economy (haben so viele Leute schon dran gearbeitet, trotzdem haben viele noch über Krieg [internationale Grabenkämpfe] nachgedacht und Sklaven via Influenz (Gluten, Zucker); Was aber wäre Bedingung für die Zusammenarbeit aller Menschen und Nationen? Ursachen!
  
  VS.
  
  Gute Gründe:
  
  Wer will was? Wer darf was haben? Geld, Autos, Häuser, Schönheit; aber insbesondere Sex: Wer hat gerade keinen Sex? (der Trieb in uns, der immer zur Geltung kommen will)
  
  sex at core; Sex [haben] ist Voraussetzung für:
  
  einiges an Reflexionspotential
  
  Worüber überhaupt nachdenken/reflektieren?
  
  Reflexion über (um vernünftig zu bleiben in Gesellschaft): keine wirkliche Konstruktion möglich, weil Macht (z.B. Influenz via eye blocker, Militär, Arbeitgeber [im Kontext der (globalen) Ökonomie: niedrigere Löhne in andern Ländern, Lohnsenkungen, weniger Arbeit verfügbar (Automatisierung, Profitoptimierung)]) zu stark (jede Nation will irgendwie mächtig sein, Influenz ist Gift für die Gesellschaft: man wird angegriffen (Locks sind stärker geworden), Polizei kann nichts tun: MAN KANN SICH AUF NICHTS VERLASSEN.
  
  Außer? Ursachen ...
         (gute Gründe findet jeder, klar, wir sind ja Individuen und wollen alle selbstständig denken, aber eine Rückbindung (= eine Religion) zu haben an logische Prinzipien, sowas war bisher undenkbar [und die Kirche hat sich wirklich viel darüber Gedanken gemacht...])
  
  ...und einen Willen zur Konstruktion und der Wille muss gebildet werden über eine Entscheidung, der hiermit Ausdruck verliehen wurde.
