#+Title: Mastering the mind to be healthy/balanced again (in a society [to be constructed])
René Tobner, EIN Philosoph der Reflexion (dennoch: der ursprüngliche...)
https://github.com/wissens-werker/vita/blob/master/pics/My%20identity%20card%20_%20Personalausweis.mp4?raw=true

(some picture has been taken from my room, here the original; I was told to remove references from my room under delusion...)
https://github.com/wissens-werker/vita/blob/master/pics/y-combinator-missing.jpg

A question which can finally be answered:
Was kann man erhoffen? What's there to hope for, if Santa Clause and other merry stories are mere fairy tales?

[edit] note on smooth economy, ironing out frictions
[edit] Is there a devil?

* Personal Health and Social Health

individual vs. society ("I" vs. "We")

What is possible for us? Is there a god? What's the best society to live in, to flourish?

I found my own health in privacy:

OWN NATURAL HEALTH
-------------------------------------------------------------------------------------------
cf. reflexivity, symmetry here (math is natural) https://en.wikipedia.org/wiki/Equivalence_relation

- the BODY in symmetry:
  - bestform of animals in general
  - same action, both sides
  - balance
  - pain on one side, try other side; Why press the hurting side, if pressing the other side will yield some effect? (stream pressure system of the body)
  - also: using your eyes to AIM at sth. near/far [micro-, macrovision]
    - the animal: a hunter
  - RINSING with ginger-citrus-tea, small-bottle-trick
    - fast head, fast work: https://youtu.be/tOigw7JRU7I
    - https://youtu.be/DeTAg51meI4
    - Yay result: https://github.com/wissens-werker/construct/blob/master/vids/Yay!.mp4
    - NUTRITION IMPORTANT: https://github.com/wissens-werker/construct/blob/master/vids/healing-faster.txt
      - gist: rice and rinse (+ fat, [fruit-] sugar), BUT: meat and sleep
    - Way to Yay (sit scar rinse): https://github.com/wissens-werker/construct/blob/master/vids/Yay-surig-medium-hot-water-at-fingertips-press-head.mp4
      - SURIG and medium hot water to press the scar, drink same before, be careful lying down, if unwell, fast stand up, have trust in swing (and hold your chin), bottle trick @ upper middle of forehead; HUGE SCAR, HUGE DANGER, how big is the scar? how to measure this?
      - at your own risk... and ah right gluten drawing... be careful! but safest method so far!
      - could do better trainings vids with better equipment... 
  - feeling body/muscles via THC consumption
    - BEWARE: if natural head stream block is too big, DANGER while controlling your movement may result!

*AND*

- the MIND and its reflection (also see bottom /human event machine/, beware shock, at first)
  - AIMING at X
  - having the identity: f(x) = x + some JUDGEMENT (is it worth to continue aiming at X, or: keeping it in mind as a valid fact?): 
    -     Is X attractive? Ok, go for it, I want to have this beautiful thing, person etc.
    - or: Is X a valid fact making sense with other facts I collected in my memory?
      - Yes, well done brain! (beauty,   no doubt)
      - No? Confusion!        (ugliness,    doubt)


-------------------------------------------------------------------------------------------


If above is true, WHAT'S LEFT (beyond being a /human event machine/, your own bio record, and the evolutionary big picture, see note(*) below!) to think about for us as ppl IN NEED of living together?

HEALTH OF SOCIETY

Is there a god? Is there sth. GOOD in society?

No, it's so difficult for us to find a common denominator. I vs. We. What we can rely on is a well governed free market and good education. We have to CONSTRUCT it working together: technology is with us. A new (digital) Commonwealth! (How easy is it to setup a company in Estonia? Easier than Germany, and yet, so much more can be improved upon via digital infrastructure to iron out economic frictions...)

    - related: Is there a devil? No problem whatsoever to work against each other. Also, structural MISCONFIGURATION (e.g. employer-employee-relations) and CORRUPTION (via influential methods [money, gifts etc.] resulting in dependent relationships which may form strong, oppressive hierarchies) will work in favor of the "devil", DECONSTRUCTING, damaging society.

To (try to) DECIDE for the CONSTRUCTIVE GOOD in society (even after: heavy war wounds, being low on ressources/money, being in want of revenge): think about what happened after World War II, all those ruins of buildings and ppl, but slowly reviving trade, schools, civility; it was good for some time...


DECIDE! (It's really always the same shit over and over again.)



pros:
- most of the illnesses of ppl are gone (dysfunctional vs. functionnal), i.e. ppl being their own doctor (having medical personnel to to surgery [dealing with fractures etc.] impossible to neglect, but psychiatry and minor illnesses [regular flue etc.] could be completely excluded from medical care)




-----------------------------------------------------------------------------------------------

BEWARE: Das menschliche Tier kann sich nur im Sozialen vereinzeln!

** TODO evolutionary big picture vs. own bio record:
-- rework section below and integrage this one
Seeing yourself as a result of evolution, random development of animals on this our earth, with humans as a kind of animal developing very sophisticated languages -- instead of being only your biographical record of family, friends, and foes.

** human event machine / thinking (reflection) about events (inner/outer) / AI
- personal vs. social intelligence
  - mutual enrichment of the personal and the social (growing language, growing tradition, growing brain)
    - i.e. our cultural evolution, what makes us human!
    - cultural evol. vs. natural one
- ONE CYCLE, ONE THOUGHT (sequential, concept of event machine from programing languages [PL] makes sense, i.e. node.js event loop): what do we do with it?
  - constructing coherent "picture" of the world we peceive
  - memory of coherent thoughts we do not doubt (how to we commit information to our memory? how is it encoded? Does Church encoding play a role?)
  - memory of thoughts we do doubt (plus: undecidable ones, anyway: non associative to valid facts collected)
    - makes our thinking slower by making us inclined to revalidate already established coherent facts (to keep our world view intact/coherent)
  - PANDORA'S BOX:
    - free -- but mechanical -- will of the human machine :: adding new ideas to our set of coherent thoughts / our valid personal record
    - some (un-)safety in big picture: random evolution on this planet, social intelligence, an ABIOGRAPHICAL record we miss most of the time
- the world of a host should be enough to life forms to flourish, proven by humans acting in my world with agents; how to do it with artificial agents?
