#+Title: pandemic vs. muscle head aches
René Tobner, Philosoph der Reflexion


* pandemic vs. muscle head aches / Pandemie vs. Muskelverhärtung am Kopf

- pandemic in germany started january 2019 / Pandemie in Deutschland begann Januar 2019
  - Is there a practical method of healing? / Gibt es eine einfache Heilmethode?
  - Is there proof about effectiveness of vaccine? / Hilft der Impfstoff wirklich?

- world-wide the ppl got so sleepy / weltweit sind die Menschen so müde geworden

  - what's the problem? / woran liegt das?

    - the virus is impacting the muscles, esp. head muscles / der Virus macht die Kopfmuskeln hart
      - gluten may worsen this effect / Gluten (Weizenbrötchen etc.) kann diesen Effekt verschlimmern
      - try it out and feel your head, is there bump? / den Kopf abtasten, gibt es eine Unebenheit??
        - hot water with some acid (e.g. citrus, vinegar) / heißes Wasser mit Säure (z.B. Zitrone, Essigsäure) hilft diese Unebenheit auszugleichen


  - as a result / in Folge dessen:
    - tiredness, less face activity (smiles)  / Müdigkeit, weniger Gesichtsaktivität (Lächeln etc.)


  - the remedy / die Heilung:
    - I had a huge bump, so I look very tired / Ich hatte eine sehr große Unebenheit, deswegen sehe ich noch sehr müde aus: I [[vids/Yay-surig-medium-hot-water-at-fingertips-press-head.mp4]]
      - sit as long as possible to release jaw / sitzen so lange wie möglich um den Kiefer zu lösen! (releasing it while lying down might not work: *danger* / diesen im Liegen zu lösen mag nicht funktionieren: *gefährlich*)
    - but as a result I can smile again / aber in folge dessen fühlte ich mich wieder munter!
      - [[vids/Yay!.mp4]]
    - nutrition / Ernährung:
      - rice (+ fat, [fruit-] sugar), BUT: meat and sleep
      - Reis (+ Fett, [Frucht-] Zucker), ABER: Fleisch zum Abendessen
    - ALSO really important to be safe, see: symmetry and other-side-press below


- René Tobner, Röntgenstraße 19, 54292 Trier, WG1 (Weiß, Neugebauer, Wiegleb)

https://github.com/wissens-werker/vita/blob/master/pics/My%20identity%20card%20_%20Personalausweis.mp4?raw=true

https://github.com/wissens-werker/vita/blob/master/pics/y-combinator-missing.jpg


* Mastering the mind to be healthy/balanced again (in a society [to be constructed])

A question which can finally be answered:
Was kann man erhoffen? What's there to hope for, if Santa Clause and other merry stories are mere fairy tales? What stories are even left to tell? Only this one about slavery vs. freedom (among other topics) in a human head!

[edit] note on smooth economy, ironing out frictions
[edit] Is there a devil?

** Personal Health and Social Health

individual vs. society ("I" vs. "We")

What is possible for us? Is there a god? What's the best society to live in, to flourish?

I found my own health in privacy:

OWN NATURAL HEALTH
-------------------------------------------------------------------------------------------
cf. reflexivity, symmetry here (math is natural) https://en.wikipedia.org/wiki/Equivalence_relation

- the BODY in symmetry/balance/beauty/gleichgewicht:
  - bestform of animals in general means to be fully symmetric
  - testing symmetry: same action, both sides


  ACHIEVING SYMMETRY? head first!
  (Wie Gleichgewicht finden? Im Kopf zu erst.)

  VIA: while rinsing (1) you have to obey other-side-press (2)

  1. RINSING with ginger-citrus-tea or SURIG-tea, small-plastic-bottle-lukewarm-water@head
    - fast head, fast work: https://youtu.be/tOigw7JRU7I
    - https://youtu.be/DeTAg51meI4
    - Yay result: https://github.com/wissens-werker/construct/blob/master/vids/Yay!.mp4
    - NUTRITION IMPORTANT: https://github.com/wissens-werker/construct/blob/master/vids/healing-faster.txt
      - gist: rice and rinse (+ fat, [fruit-] sugar), BUT: meat and sleep
        - GLUTEN GOOD ENERGY, TOO!
    - Way to Yay (sit scar rinse): https://github.com/wissens-werker/construct/blob/master/vids/Yay-surig-medium-hot-water-at-fingertips-press-head.mp4
      - SURIG and medium hot water to press the scar, drink same before, be careful lying down, if unwell, fast stand up, have trust in swing (and hold your chin), bottle trick @ upper middle of forehead; HUGE BUMP, HUGE DANGER, how big is the bump? how to measure this?

  2. pain on one side, try other side first; Why press the hurting side, if pressing the other side will yield some effect? (stream pressure system of the body)
    - DRY SPOTS/KNACKEN: apply acetic acid (vinegar essence, Essigsäure, e.g. SURIG) with water, first to the dry spot, than other side, too, and press carefully!
    - or: just other-side-press [above LEFT ear!] to avoid LEFT cheek press (LEFT? side with no knacken/cracking here)
      - better with SURIG (vinegar acid) water






  ADDITIONAL TRAININGS:

  - feeling body/muscles via THC consumption
    - BEWARE: if natural head stream block is too big, DANGER while controlling your movement may result!

  - using your eyes to AIM at sth. near/far [micro-, macrovision]
    - the animal: a hunter, hunting down prey (far away first, nearby then)
      - this is what all animals do, finding some nourishment to sustain themselves
    - we do not have to hunt, we can just have a walk, and yet we find things on the way

*AND*

- the MIND and its reflection (also see bottom /human event machine/, beware shock, at first)
  - AIMING at X (so wie man mit den Augen etwas fokussiert, so fokussiert/zielt auch der Geist, das Gehirn)
  - having the identity: f(x) = x + some JUDGEMENT (is it worth to continue aiming at X, or: keeping it in mind as a valid fact?):
    -     Is X attractive? Ok, go for it, I want to have this beautiful thing, person etc.
    - or: Is X a valid fact making sense with other facts I collected in my memory?
      - Yes, well done brain! (beauty,   no doubt)
      - No? Confusion!        (ugliness,    doubt)


-------------------------------------------------------------------------------------------


If above is true, WHAT'S LEFT (beyond being a /human event machine/, your own bio record, and the evolutionary big picture, see note(*) below!) to think about for us as ppl IN NEED of living together?

HEALTH OF SOCIETY

Worauf lohnt es sich zu zielen, wenn man ein langfristiges Gut (a long term good goal) im Auge hat? What does/can /good governance/ mean?
Is there a god? Is there sth. GOOD in society?

No, it's so difficult for us to find a common denominator. I vs. We. What we can rely on is a well governed free market and good education. We have to CONSTRUCT it working together: technology is with us. A new (digital) Commonwealth! (How easy is it to setup a company in Estonia? Easier than Germany, and yet, so much more can be improved upon via digital infrastructure to iron out economic frictions...)

    - related: Is there a devil? No problem whatsoever to work against each other. Also, structural MISCONFIGURATION (e.g. employer-employee-relations) and CORRUPTION (via influential methods [money, gifts etc.] resulting in dependent relationships which may form strong, oppressive hierarchies) will work in favor of the "devil", DECONSTRUCTING, damaging society.

To (try to) DECIDE for the CONSTRUCTIVE GOOD in society (even after: heavy war wounds, being low on ressources/money, being in want of revenge): think about what happened after World War II, all those ruins of buildings and ppl, but slowly reviving trade, schools, civility; it was good for some time...


DECIDE! (It's really always the same shit over and over again.)



pros:
- most of the illnesses of ppl are gone (dysfunctional vs. functionnal), i.e. ppl being their own doctor (having medical personnel to to surgery [dealing with fractures etc.] impossible to neglect, but psychiatry and minor illnesses [regular flue etc.] could be completely excluded from medical care)




-----------------------------------------------------------------------------------------------

BEWARE: Das menschliche Tier kann sich nur im Sozialen vereinzeln!

** evolutionary big picture vs. own bio record/career/wrong and right actions in bio record
Seeing yourself as a result of evolution, random development of animals on this our earth, with humans as a kind of animal developing very sophisticated languages -- instead of being only your biographical record of family, friends, and foes.

Even technology to overpower others came into some hands by random. There is no justice in random development. Justice is established by having principles and rules (e.g. laws derived by principles of humanity like not killing others). But what principle lies at the very bottom of humanity? It's the decision for "construct". And everybody needs to agree to that, to have an everlasting empire... "construct" implies constructing together, therefore employer-employeer-relationships must be managed well by everyone, and supported by digital infrastructure.

Having the smarts via rinsing has the potential to enable "construct", if appropriate learning is achieved.

Otherwise corruption via two-class-society will creep in again, so no eternal empire possible.

** human event machine / thinking (reflection) about events (inner/outer) / AI
- personal vs. social intelligence
  - mutual enrichment of the personal and the social (growing language, growing tradition, growing brain)
    - i.e. our cultural evolution, what makes us human!
    - cultural evol. vs. natural one
- ONE CYCLE, ONE THOUGHT (sequential, concept of event machine from programing languages [PL] makes sense, i.e. node.js event loop): what do we do with it?
  - constructing coherent "picture" of the world we peceive
  - memory of coherent thoughts we do not doubt (how to we commit information to our memory? how is it encoded? Does Church encoding play a role?)
  - memory of thoughts we do doubt (plus: undecidable ones, anyway: non associative to valid facts collected)
    - makes our thinking slower by making us inclined to revalidate already established coherent facts (to keep our world view intact/coherent)
  - PANDORA'S BOX:
    - free -- but mechanical -- will of the human machine :: adding new ideas to our set of coherent thoughts / our valid personal record
    - some (un-)safety in big picture: random evolution on this planet, social intelligence, an ABIOGRAPHICAL record we miss most of the time
- the world of a host should be enough to life forms to flourish, proven by humans acting in my world with agents; how to do it with artificial agents?
