#+Title: Mastering the mind to be healthy/balanced again (in a society [to be constructed])
René Tobner, EIN Philosoph der Reflexion

[edit] note on smooth economy, ironing out frictions
[edit] Is there a devil?

* Personal Health and Social Health
  
individual vs. society ("I" vs. "We")

What is possible for us? Is there a god? What's the best society to live in, to flourish?

I found my own health in privacy:

OWN HEALTH
-------------------------------------------------------------------------------------------

- the BODY in symmetry:
  - same action, both sides
  - balance
  - pain on one side, try other side
  - also: using your eyes to AIM at sth. near/far [micro-, macrovision]
    - the animal: a hunter
  - RINSING with ginger-citrus-tea, small-bottle-trick
    - https://youtu.be/DeTAg51meI4
  - feeling body/muscles via THC consumption
    - BEWARE: if (un-)natural headlock is too big, DANGER while controlling your movement may result!

*AND*

- the MIND and its reflection (also see bottom /human event machine/, beware shock, at first)
  - AIMING at X
  - having the identity: f(x) = x + some judgement:
    - Is X attractive?
    - Is X a valid fact making sense with other facts I collected in my memory?
      - Yes, well done brain!
      - No? Confusion!


-------------------------------------------------------------------------------------------


If above is true, WHAT'S LEFT (beyond being a /human event machine/) to think about for us as ppl IN NEED of living together?

HEALTH OF SOCIETY

Is there a god? Is there sth. GOOD in society?

No, it's so difficult for us to find a common denominator. I vs. We. What we can rely on is a well governed free market and good education. We have to CONSTRUCT it working together: technology is with us. A new (digital) Commonwealth! (How easy is it to setup a company in Estonia? Easier than Germany, and yet, so much more can be improved upon via digital infrastructure to iron out economic frictions...)

    - related: Is there a devil? No problem whatsoever to work against each other. Also, structural MISCONFIGURATION (e.g. employer-employee-relations) and CORRUPTION (via I etc. resulting in slavery) will work in favor of the devil, DECONSTRUCTING, damaging society.

To (try to) DECIDE for the CONSTRUCTIVE GOOD in society (even after: heavy war wounds, being low on ressources/money, being in want of revenge): think about what happened after World War II, all those ruins of buildings and ppl, but slowly reviving trade, schools, civility; it was good for some time...


DECIDE! (It's really always the same shit over and over again.)



pros:
- all the illnesses of ppl are gone (dysfunctional vs. functionnal), i.e. no more hospitals!



(*) Beware: Das menschliche Tier kann sich nur im Sozialen vereinzeln!


** INFO human event machine / thinking (reflection) about events (inner/outer) / AI 
- personal vs. social intelligence
  - mutual enrichment of the personal and the social (growing language, growing tradition, growing brain)
    - i.e. our cultural evolution, what makes us human!
    - cultural evol. vs. natural one
- ONE CYCLE, ONE THOUGHT (sequential, concept of event machine from programing languages [PL] makes sense, i.e. node.js event loop): what do we do with it?
  - constructing coherent "picture" of the world we peceive
  - memory of coherent thoughts we do not doubt (how to we commit information to our memory? how is it encoded? Does Church encoding play a role?)
  - memory of thoughts we do doubt (plus: undecidable ones, anyway: non associative to valid facts collected)
    - makes our thinking slower by making us inclined to revalidate already established coherent facts (to keep our world view intact/coherent)
  - PANDORA'S BOX:
    - free -- but mechanical -- will of the human machine :: adding new ideas to our set of coherent thoughts / our valid personal record
    - some (un-)safety in big picture: random evolution on this planet, social intelligence, an ABIOGRAPHICAL record we miss most of the time
- the world of a host should be enough to life forms to flourish, proven by humans acting in my world with agents; how to do it with artificial agents? 
