#+Title: Mastering the mind to be healthy/balanced again (in a society [to be constructed])
René Tobner, EIN Philosoph der Reflexion

[edit] note on smooth economy, ironing out frictions
[edit] Is there a devil?

individual vs. society ("I" vs. "We")

What is possible for us? Is there a god? What's the best society to live in, to flourish?

If this is true:


- the MIND and its reflexion (AIMING at X; having the identity: f(x) = x + some judgement:
                              Is X attractive? Is X a valid fact making sense with other facts I collected in my memory? Yes, well done brain!  No? Confusion! )
  
  - related: Is there a god? Is there sth. GOOD in society? No, it's so difficult for us to find a common denominator. I vs. We. What we can rely on is a well governed free market and good education. We have to CONSTRUCT it working together: technology is with us. A new (digital) Commonwealth! (How easy is it to setup a company in Estonia? Easier than Germany, and yet, so much more can be improved upon via digital infrastructure to iron out economic frictions...)

    - Is there a devil? No problem whatsoever to work against each other. Also, structural MISCONFIGURATION (e.g. employer-employee-relations) and CORRUPTION (via I etc. resulting in slavery) will work in favor of the devil, DECONSTRUCTING, damaging society.

- to (try to) DECIDE for the CONSTRUCTIVE GOOD in society (even after: heavy war wounds, being low on ressources/money, being in want of revenge): think about what happened after World War II, all those ruins of buildings and ppl, but slowly reviving trade, schools, civility; it was good for some time...

  
THEN: decide. (It's really always the same shit over and over again.)



[...]



(*) Beware: Das menschliche Tier kann sich nur im Sozialen vereinzeln!
