* How to plan/construct for the world? How to have happiness for all? / Ist Glück für alle praktisch möglich? Wenn, dann nur so:
- thinking about it, write it down
  - [[./world-wide-wished-for-things.org]]
  - Why not only communication from citizen to citizen, politician to politician? (our world got so complicated, so many nations evolving, so many attempts makings sense of people's characters, viewpoints...)
    - good as long as results are recorded/merged in the plan (=one data model [1DM], one central authority [1CA])
    - the real problem in the world: *too many CAs* of nations and other players, not willing to give in to one CA
    - moving to 1CA while keeping nations/ppl proud/happy is the logical conclusion of the *too many CAs* problem
      - Wasn't there something like international German/English? :-)
        - which had to develop itself via communication on an relatively aligned and active (not sleeping) host, well, 3 years ago, so much polarization, wait wat? /total reflection/ (semanitcally connected to the term /polarization/) and having symmetry produced via optics? to have balance in symmetric doubt, the undecidability? [AI]
          - https://en.wikipedia.org/wiki/Total_internal_reflection
            - internal?
      - Wasn't there something like [[./weltbuehne.org]] ?
        - one day's hard labor in my realm stage (nowadays purgatory, inferno hopefully done) with so many directors, hopefully the last

- and implement some important goals of this plan, gather feedback, optimize the plan
  - rinse and repeat to have some paradise won in time

- [alignment] How to have HAPPINESS with your own body? Resolving (?) the distinction (dualism?) of body and mind resulting in more body (beauty/symmetry) and more mind (/quickthink/).
  - as with meat: You have to believe it.
    - head first symmetry means: getting the jaw out / den Kiefer ablassen (AT YOUR OWN RISK!)
      - https://youtu.be/QFbVg6nehyA
      - https://vimeo.com/554218337
      - [[./vids/Yay-surig-medium-hot-water-at-fingertips-press-head.mp4]]
  - more advice BELOW "body in symmetry"
    - see symmetry and other-side-press below (LESS RISK)
  - *AT YOU OWN RISK*

- If you can be HAPPY with others depends on the plan mentioned ABOVE

- /quickthink/ was def. missing in some important realm of discourse (What brought us here? How to play against this host, bringing health plus a simple and whereby brilliant plan to cope with the world? Smart play: too daunting, better make players dumb, how to get out of it? Ok, this realm got smart again or is working on it, but what about the world?)

#+BEGIN_SRC
  To be smart for yourself: your smarts  might outwit   someone else
  To be free  for yourself: your freedom might endanger someone else
  - free market has same problem, but to see the problem...
#+END_SRC

** The free market and governance problem (not to forget)

- regarding the distribution of goods: a well-governed free market/economy even by digital means seems like a contradiction in itself: how can a market be free and governed at the same time?
  - to circumvent this contradiction the claim is: we can do it somehow via digital infrastructure, which includes the state to some degree, so that it can be well-governed and free at the same time (and not go bankrupt every few decades)

The market:
  - free actors (may also try to force governance)
  - vs.
  - unfree actors (forced by too free/powerful actors)
  - vs.
  - governance by a government (a trying to be neutral entity [das Allgemeinwohl, Neutralität gegenüber allen Bürgern, im Auge: der Staat])

** Reminder again on 1CA = 1 plan = world-wide-wished-for-things
A functional state for functional citizens. Everything needs to be optimized, not only your own body, that's the gold standard. What else to aim for?

#+BEGIN_SRC 
more shifts
more ppl in work
more party
#+END_SRC

- see heading "economics" in: [[./world-wide-wished-for-things.org]]

** Being sceptical about personal contact condoning this plan OR THIS HEALING METHOD!!!
- THE SURPRISE OF BEST FORM OF HUMANS (beauty, smarts)
  - but: Body -> Mind -> coop and plan (knowing what can go wrong, avoid being drunk with power)
  - [[vids/Body%20-&gt%3B%20Mind%20-&gt%3B%20coop%20and%20plan%20(gt%3Dgreater-than,%20gr%C3%B6%C3%9Fer-als-Symbol).mp4][vids/Body -&gt; Mind -&gt; coop and plan (gt=greater-than, größer-als-Symbol).mp4]]
  - [[./world-wide-wished-for-things.org]]

- sit (scar) rinse and other-side-press opening the lock:
  - [[vids/Yay%20out%20of%20network%20sit%20scar%20rinse.mp4][vids/Yay out of network sit scar rinse.mp4]]
  - sit as much as possible
    - but: lie down rinsing through when you feel laid back by the stream and other-side-press, get up when too many cracks on the right side
    - [[vids/Yay%20lie%20down%20necessary%20too%20but%20not%20too%20long.mp4][vids/Yay lie down necessary too but not too long.mp4]]
  - alignment will get better eventually, releasing neck and head, making these upswings possible:
    - [[vids/Yay-Release%20at%20left%20back%20head,%20heavy%20upswing,%20shoulder%20arm%20backstretch.mp4][vids/Yay-Release at left back head, heavy upswing, shoulder arm backstretch.mp4]]
    - yes, it looks crazy, but this 3 year headlock... that it's possible to release, well it is!
  - the (natural) lock/grip and the matrix, too much!
    - [[vids/how to wake up from the matrix this double world-JSdAW47zxHo.mp4]]

- water-in vs. water-out (water with you and other-side-press)
  - too much pressure, why not have a pee? be careful moving / zu viel Druck, warum nicht pinkeln gehen? Vorsicht dabei und auf der andern Seite drücken (always water with drink with whatever body part / immer Wasser dabei und mit allen möglichen Körperstellen trinken)

- energy by: pancakes, rice, sugar, fat in the morning, later on better meat (mince, Hackfleisch, Tuna -> no connections to you!)
  - esp. when feet get cold / ganz besonders dann, wenn man kalte Füße hat
  - just had two rinses in the morning, still not aligned but better, luckily some bread and pancakes in the kitchen, now some more, but mostly resting on double yoga mat, comfy cushion under head, feed only on one mat, sleept for a while, remembering dreams about tech bravery everywhere spread by testbed Germany
  - when sleeping, have door locked for safety! / beim Durchspülen Einschlafen = Sicherheitsrisiko => Tür verschließen!
  
