* <2021-06-05 Sa>
Me stupid
- everyone can die in KQ
- too much content produced with devils convincing me of their command, but my command needs time to be enacted, so I just should rinse.
- Trier (only Chrissi in command, actually) command: real economy back, see [[news.org]] "reality management"
  - ppl need occupation / Beschäftigung außer you know what
    - {with: Thomas Burch, TCDH, major commanding devil by it's "KQ seriou" threat, some guy enraged by split of sexes (@Burch: You will die, if you stay neutral! (not for or against me)) because of me and all a game against me, one and a hald year ago, because rinsing not allowed, too much freedom suddenly}
  - see note about psychology below: "DIE GANZE PSYCHOLOGIE UNNÖTIG"
    - {with: Wolfgang Lutz, Psychotherapie Ambulanz Trier}
  - this "merry" play:
    - die Freiheit für alle [genügend Teufel wussten ja vom Rinsen, hatten vielleicht ab und an genügend Freiheit dadurch] sollte zu Grabe getragen werden, er kann ja nicht mehr Durchspülen und dabei soll er's zeigen, irgendwie, aha, so'n Quatsch; und was soll hier dann eigentlich gespielt werden? Überleben bei den Teufeln, und was machen die Teufel: Mädels succumben mit meinem Foto, ficken und optional töten sowie Kissenficker beschämen und eliminieren, und dafür gibt's Geld und frei ficken im IAT; IATF: freche Bechterev Rinser mit Equipment -- so much chaos, in Frankfurt Main and elsewhere, later on gluten with natural locks done by Sepherin, too; chaos ever more spreading, E-Mails, I, proof of conscience, key players locked... wake up with sit rinse and real economy back (ppl allowed to work again), pandemic needs to end!
* <2021-06-04 Fr>
- My neutrality was helpful to save some reasonable thinking in this repository humanity was waiting for about 2000 years, (sit) rinsing a new culture technique among this knowledge, am I really the only one? Coming out of a 3 year lock... and not only Mr. Trump, it's a general problem, but he was made it so!
  - Too emotional and too ugly, René, do it better! Nich nur: Respekt vor Frauen -> Respekt vor Freiheit (
    
    was war Werder vor meinem KQ? Meine Versicherung [und überall wo ich auftauchte war natürlich dann auch von der Versicherung die Rede] und mehr oder minder gütliches Succumbing, naja und Arbeiter "ausbilden" (was wirklich schlimm genug ist, aber ja, was macht man mit dieser Macht)... jetzt könnte aber mal Gottes Werk und Teufels Beitrag abgeschlossen werden mittels Coop Construct
    
    (meine Ausbildung als neutraler Arbeiter, Wissensarbeiter letztendlich, dass das so anders werden könnte, naja Gesundheit und Prinzipien, auf einmal sind sie da [und ja auch eigentlich 3 Jahre alt]... aber dieses Zusammentreffen, diese Koinzidenz [und bis ich das so genannt habe, war ich safe played, derweil in Deutschland Morde immer mehr Tagesgeschäft; und dennoch am Anfang Kissenficker, glückliche Pärchen, und Leute, die sich versuchen zu alignieren, auch per Rinse, dann aber Atombombendrohung und anderer Terror] hier bei mir zu haben, das allein ist schon die größte Errungenschaft der Menschheit [dieser Streit, dieser Austausch der Meinungen] bisher, Zivilisation blieb naturgemäß -- Recht des Stärkeren -- auf der Strecke, aber Kultur ist jetzt eigentlich sehr viel besser vermittelbar, nur ohne Zwang und sit rinse ging garnix... und sit rinse bedeutet den Kopf durchzuspülen [mit Essig-Tee die ganzen Ablagerungen raus: "natürliches" Lock was sich über unsere Lebenszeit ergibt], sich fit und leicht zu fühlen, die Gesundheit ist mit diesem Training herstellbar, es ist so verdammt lächerlich, wer will denn nicht komplett gesund sein? Dass dann auch alle komplett schön sind, ist natürlich ein Ding der Unmöglichkeit ... aber was ist alles damit gewonnen? Krankenhäuser: so viel mehr überflüssig, die ganzen Wehwechen; dazu noch DIE GANZE PSYCHOLOGIE UNNÖTIG

    [bisherige Psychologie-Praxis: auch vielfach nur als Spiel verstanden: Leute als Kommunikationshosts + dieselben irgendwie verwalten; richtige Gesundung, so wusste man, war nur möglich mit Bezug auf Körper und Geist; Analyse von Geisteskrankheiten und Pharmazeutika definitiv keine persönliche Gesundungs-Lösung; nichtsdestotrotz war es schwierig mit der Gesellschaft an sich, die Menschen in ihr, die Verteilung der Macht und Influenz immer stärker, Austerität immer stärker -- so und dann noch dieses Spiel gegen mich und man musste unbedingt gegen mich sein {Freiheit, Rinsen nicht erlaubt}, sonst wird man reingeritten {mit: Wolfgang Lutz, Psychotherapie Ambulanz Trier}]

    SONDERN: einfach nur noch dieses prinzipien-orientierte Denken: Reflexion - Symmetry - Konstruktion, [kein nat. Prinzip, leider...])
    
    UND mittels pares inter pares [Gleiche unter Gleichen] via sit rinse -- alles noch so neu, aber bloß nicht nochmal diese ganze Scheiße...
    
    )


  - https://youtu.be/VzIm0TxMdlU
  - Download: [[vids/Be-brave-and-rinse-and-dont-forget-reason.mp4]]
    - (but: it is not allowed for some)
- My neutrality and return to health via rinse and energy vs. severity/seriousness/austerity (austerity? -> https://www.dict.cc/?s=Ernst), which can unfold in any network without principled communication/reasoning in one central authority (1CA) 
  - Too forgetful about all the endangerment...
    - "Es hätte nicht so ernst sein müssen." / "It didn't had to be that serious." ?
      - My wishful thinking and that of others, to be doomed and extinguished by confusion and traditional convictions and sex and money. "
      - Es war natürlich so verdammt ernst. / It really was so damn serious.
  - https://youtu.be/H6tkYIyieWA
  - Download: [[vids/Meine Neutralität u Gesundung per Rinse und Energie vs. Ernst, der sich im Netzwerk entfalten kann.mp4]]
  - my neutrality? [[why.org]] -> "decisions", "free will"

#+BEGIN_SRC 
this austerity, this violence,
this hard-won? personal joy and
always some fear/envy left about your privileges
or those of others
VS.
that bliss (Wonne, Glücksseligkeit) somewhere else, where could it be?
#+END_SRC

* Wasn't there something like ...
  - making devils act or acting devils on their own (inviting other devils), making me whereby act on this angry world (produced in a night of communicating terror against me [some note on C, I took down again in great fear, but everybody knows? -- A video about me being locked and until unlock someone else is king]), producing this introductory text to Construct, no one dared to think of to be convincing; how much doom was again in my realm and on earth and last but not least me, was it worth it? The ultimate game of society. How to control it? :/
  - Naja, "besser scheitern" und work in progress, mostly done by IAT devils I should not befriend again, but most of them were just driven against me, also my philosopher "queens" (Is it allowed to be queen? Is it allowed to be a king? Mostly women were /left/. Fleisch and Ficken was the only safety/career/alignment personal-and-clan-philosophy available. Endangered civilization, economy etc. to the max. Military had to intervene and make some space for reason...) know that, alas, a play is needed to make me fear.
  - Alas again, IAT devils inviting other devils intensifies the whole atmosphere to the utmost (some even peed themselves, really the terror of, oh, it's the last day and René might have no incentive to give handshakes). Better no old MHTs (with neural net, which is even not that important for feeling fear of others is easily receptible by one's mind [powerful agitators in my realm can dwell on the fear of others]). This is really some virtual reality! Yes and no: maybe, but only maybe, more realistic and useful for society than Quake, not necessarily better. :P
  - I wish we had had virtual reality all the time (only virtual blood).

* Some doubts about carrying out this plan, advice, so many things to look into, but how long to keep exploring the design space? research vs. practical applications
- seems too good and too laborious? (digital infrastructure :P), many kings and queens died ...
- real detailed planning and including nations will take at least X months
- being sceptical about personal contact condoning this plan
- not to distract or belittle the dangers, but MHT neural net mindsharing via long term exposure to a host (neural net as mediation layer between host and MHT client), what does that mean for humanity? Sharing thoughts and feelings so easy. Sharing more concrete knowledge like drawings on a chalkboard? How precise the communication can get? What can technology do to increase this experience? Example of precision when having MHT-computer communication (man-machine-interface): moving a pointer on a screen: the most important faculty of the mind: aiming and focussing on sth. translated onto the machine. Learning about my body movements and making a roboter move, translating this experience?
  - host resurrection via pancakes, nutella, banana, crunchy peanut (dm) as energy to sit rinse:
    - energy alignment: [[vids/Yay-surig-medium-hot-water-at-fingertips-press-head.mp4]]
    - but: meat and sleep (or better: meat [or similar already] at midday)
