*** What happened in me
unfolding - folding - unfolding (from new consented seed)

The brave new world of Mr. Tobner (Mr. Feiler in spe) and ppl exploring the newly found design space within me
Intellectual tour de force of human species on planet Earth
The pieces of power gathered around me, arranging a marriage of heaven and hell.
Some "good" coffee with some friends and foes mediating a modest proposal by Mr. Jonathan Twist (Oliver Twist vs. Jonathan Swift)
A tale of two worlds --  what could emerge out of it?
Königs-Quest: Was hat der neue König zu sagen? Man will ja schon ein objektives Bild vom Denken des Königs haben, die Gewissensprüfung mit Engeln und Teufeln.
3. Weltkrieg bei mir auf den Augen: Sklaverei gegen Freiheit
An exercise of democracy in me: What would the ppl doubt about their society?

Teufel können existieren, weil Macht immer genutzt wird. Um die Macht zu bewahren ist Geheimhaltung oberstes Gebot: Nichts darf niedergeschrieben werden.
Warum sollte sich das jetzt ändern? Warum freuen sich die Historiker schon?
Engel können existieren, wenn Macht und Wissen Hand in Hand gehen.

Freiheit der Menschen konnte bis dato immer unterdrückt werden. Sodann besonders langes Königsspiel. Königsspiel verlangt Verleumdung, wenig konsistente Kommunikation über meine Theorien. 

(Macht über Gesellschaft vs. Wissen über die vernünftige Gesellschaft)
Timeline and reflection about the Realm in my realm
The Realm inspecting me, getting used to my body, being comforted or discomforted with my political views. Doves and Hawks. Split and more inclusions for each party, pretty much world wide. Unity with some alternative to cleansing seems possible. I made thinking about this unity possible, so I have some command. (Not many influencers left opposing my vision/knowledge!)

getting used to my thinking and having (at least) one (god dam'it! :-) ) thought to unite all parties. Coincidence as event vs. coincidentia oppositorum (the folding of all opposites into one new seed to make progress with) as envisioned by Cusanus...
Insurance Bechterev all my life developing scar: ppl could inspect me or communicate via my head
Privacy and selfsex
General theme: coffee, sugar, dehydration, but at the beginning I could just stand up and drink my water, but I needed advise already for so unclear.
Poisened with sugar and dehydrated I became so green, almost. Interference, proof of consciousness began.
It became clear I could be a king. A real King's Quest.
Working under influence at LM Trier, Mr. Merten's library.
Rid into Hospital Mutterhaus Trier by play with Marco.
Run into void at Koblenz, fleeing from Isa via bike, my trusty.
Biting on chilli saved me from death, pressing my scar on the floor with gluten lock.
I've been given the leash to Mr. Trump, i.e. he had to play the major devil to me and he very much wanted so, continuing slavery.
Luzifer awakening with Frankfurt Rindswürstchen, Löwensenf Extrascharf and coffee. (Some impression for many, also Lisa already.)
Civil war play in me.
Contact with Marco almost cost my head.
Everyday levelling out with plating on my head without me knowing
Pandemic starting out in Wuhan with Influencers inspecting ppl about me being there?!
The time I was watching Star Trek Deep Space Nine: Be on your toes Mr. O'Brian.
Lisa already watching, but that's not really my man, until some footage shown.
Cheeselock (too much Parmesan and only Mate :/ , yes, Lisa liked the Cheesewoman at Edeka, too.)
Sleeping in my fathers chair and got better.
Advice about salad, fish, but then driven out to only meat.
Standing at the kitchen window sill smoking and listening to DJ Shadow and Cut Chemist (Survive Song).
Lured into sugar lock again with Ritter Sport. (This "mistake" enabled drawing via my gluten crown, was disallowed before, to have me heal.) Found Lindt 99% chocolate on my way further in lock.
Still head didn't get much better, ever more ppl in my thinking hub, thinking fast, thinking principled.
Sepherin and Bechterev acknowledge the ultimate doubt about being trained in safety/risk.
(To always be SAFE, the rule #1 of the Realm. All this FEAR to be at risk/UNSAFE known in the Realm.)
To always be at RISK. How to be truely free? I had the illusion of freedom/safety/privacy, it felt like real freedom -- really important, really the almost invisible advantage of just being human, not Realm.
How do you want to live your life?
The void to give from the current generation to the next. (When Maynard got to know about the "necessity" of evil in the world [no awakening with weed was necessary like with me], he was shaken, trembling, drugs; what's left? First anger! Why the world cannot be sober? Not easy to reason with the devil, what is reason anyway, what did he know back then? Back then only possibility left: Being somehow patient about things to come. Taking comfort in the good life, but even the vineyard felt wrong sometimes. Real Lisa was of course shaken to the ground, too.)
Having an alternative to the void: Knowing about the mechanics of the body and the mind, and about relationships:
- RISK to loose control about the one's your attracted to
- utmost SAFETY by privacy, body control, rinsing
The ultimate hope of the Realm: finally possible to have reasonable citizens by getting out of sex drive ones and thinking about reflection as basic principle of the universe, "somewhat" lucky random evolution on this planet...


Met some ppl (guys and girls) in my upper realm, who really dwelled in my realm of knowledge and became +my Realm+ (good reminder of the neutrality of this newly found realm, a swarm think realm), my predicted RandomOnes. And it is our Realm, because pares inter pares by science. This is why true power is with me. So many optimizations already planned, the Plan already so perfect? :-) Still question lingering when to realize this true power.

^What was clear was that someone really had fun in privacy and this someone was called René Tobner and was looking for a muse, called Lisa Feiler.
PPL NEEDED TO BE INCLUDED TO EXPLAIN, WHAT'S GOING ON at all^, and yet difficult to understand for what could one early interpreter understand and yet expressing what he/she understood again...alas *seufz*:
Kierkegaard: To really understand means to be able to teach it (to someone), which normally involves using your "own" words ("own"? normally when paraphrasing one CAN use one's own words, plus some newly learned [+ the common words, otherwise communication is difficult]). But if you have to get to know first the words to learn the theory?
Learning another language  is impossible without the words of the foreign tongue.
Learning about everything* is impossible without the words of the foreign thought.
*The philosophical theory thereof.
So difficult:
Realigning one's already learned words, esp. when it's about human affairs like sex, love, freedom (money is some sort of freedom), and so on.
Es musste etwas auf meinem Rücken ausgetragen werden. Erst sieht's nach Gottes Werk und /Teufels Beitrag/ aus, (/Cleansing/ -- the devil needs a chance, again! The way of the Realm [until now?] --)
und das ist es auch (noch), aber dennoch steckt der Zufall, die Einsicht in die Evolution, in unsere Entstehung (Was ist der Mensch?) dahinter. Und wenn man das verstanden hat, dann ist Gottes Werk und Teufelsbeitrag nur eine Kategorie, dann kann man die Welt neutral, irgendwie unparteiisch, betrachten. Das ist die lang' vergessene Einheit der Menchen auf diesem Planeten.
The end of story telling is reached -- just for a moment -- when someone understands this neutrality. Then (panic of) boredome ensues (What if everyone is just so relaxed? And tried privacy [control of sex drive]?), but nonono we still have ourselves to confuse us* / to play with / to learn from each other (biorecord) and to do more research into the unknown. (* one human beings acquired language is -- luckily -- quite randmon, still :P )
Die Tradition setzt auf das Geheimnis der körperlichen Alignierung.
Die Moderne setzt auf die Alignierung des Geistes, die vernünftige Menschen erschafft.

Many countries want a plan!

To all the dead-makers and slave-makers, it's all by random and by wrong education.
To all the dead and enslaved, it's all by random and by wrong education.

REST IN PEACE to all ppl who had to be extinguished during this play for my safety and for the impossibility to inform everyone about new world order, when the same is just in the making, work in progress, and is the newly found new world order really convincing? So much doubt! Still always the distinction between power and knowledge giving orientation, and with so much knowledge I could already deliver, what would be able materialize?
Now we have the ultimate doubt of the Realm fixed and how long a war do we want to prepare for? All these scenarios... and it's still so uncertain, how or if at all will survive.
Better directions, better directors.
How much more cleansing is necessary? Depends on how fast we are with educating/training ppl!
The directors can aim better now. How to aim best? Having to play on humanity still in mind?

How to restart with so much guilty conscious by victims of war?
The necessity of the devil for Bacon's theory of power that power is always used. But knowledge can be used now, too, for we found it...

Many countries want a plan!

A future for all. It exists, but we have to unveil it.

The inner and the outer. Only one time, this planet.
Really, to start from here...
Pares inter pares vs. world peace is impossible (w/o exposing I -- so much is left of unexposed I!)
One day we all can be equals, but that's some work...
My world merged in you, and your world merged in mine.
Knowledge vs. Power
Knowledge and Power
And Power can work with better Knowledge now.
The Realm -- how to get away with murder
The insurance Bechterev syndrome is just the result poor state management.
1. Everyone's struggle for a successful life. The state of one's pride. (Wie man dasteht, vor sich selbst und vor andern. Anerkennung.)
2. I can keep safe by observing my state/body and acting accordingly.

Patriarchat
Matriarchat -- the women really MADE A STAND with I and my naive musings about stable relationships? (related to gender equality)
- being in privacy once in their life, not in need to satisfy a man
  - really means: took their own flat, womenless man everywhere
  - and you know what happened...

No matter if you're shameful or not, it's still difficult to control other persons (loved one's).

How to get away with murder/slavery?
How to get away with functional humans? The devil has no clue what I am talking about! The devil needs a chance to learn this. That's everything he will get by my rule.

Influence: good/bad effects on the world, but now with the play it kept the peace, neutrality. Some ppl had to die, yes. But it is wrong that power necessarily corrupts. Functional humans can control their powers.
So many ppl in lock, yet.

Die Gewissenprüfung und wer ist nützlich, wer nicht? (some ppl asking about "how much do you want to make me kill myself?") would really a waste of human ressources...
Wie nützlich war ich? Wozu könnte ich irgendwann nützlich sein?

The marriage is done in my mind (this strange feeling we HAD to work together -- even if it was by game mechanics -- and it def. was not only my mind. Incorporating this experience in your own mind might still feel daunting and confusing, esp. with family ties shaken. Thinking about families, and love, and sex -- and all the love and sex in my realm -- I cannot remember to have married anyone! :) Well, who is the creator of this world, it's mixed: yin and yang day and night at work forming this new world for the first time in human history. Yin is weak. Yang is strong. I am weak and I am strong. Our marriage and our merry age! :P

No real evidence for this world, only reproducable via magic hat and a host???
But wait comparing notes is indeed an evidence!
I made everything fall apart by Everything, but putting it back together is should be easier now.

Pares inter pares by science! (And even kings need some consent by their subjects ... )

