** INFO Was war? Was ist? Was wird? 
- Corona?!...
- bräuchte man noch solche Pflegekräfte wie M in der Zukunft (a worker taking care of handicapped/disabled persons), wenn die Menschen so vernünftig geworden sind?
  - was will man den Menschen geben/zeigen? (neues Wissen ist verfügbar: Readme.org, bessere Wünsche: world-wide-wished-for-things.org)
  - sie könnten jetzt /Gesundheit/ UND soziale Vernunft haben
    - /Gesundheit/ schließt unglaubliche Stärke mit ein (WARUM GEHT MEIN KQ SO LANGE?)
  - EINEN Plan für die Welt ist möglich (erst recht mit Gesundheit [persönlich und sozial von Readme.org])
  - EINEN Plan zu machen geht nur wenn genügend Leute an einem zentralen Datenmodell arbeiten
    - der Kapitalismus muss besser gesteuert werden, nicht abgeschafft, freier Markt ist wichtig (das ginge auch /in Richtung/ Ressourcen-basierte Ökonomie [nie komplett ohne freien Markt, aber siehe: supply-chain-optimization@ww-wished-things], aber eben ganz klar, weil manche Ressourcen knapp werden [was ja genügend Menschen wissen: extinction rebellion, fridays for future etc.])
  - EINEN Plan zu machen und diesen stetig an neue Problemlagen anzupassen, immer weiter an diesem Datenmodell zu arbeiten; nur so kann überhaupt für die Welt geplant werden...
  - die Welt war bei mir zu Gast und so viel ist möglich
  - die Welt war bei mir zu Gast und hat sich auch gefragt, was Du davon hälst (weil es mich ja interessiert, weil die Welt sich für mich interessiert hat [dieser KQ ist so lächerlich seltsam, aber aus guten Gründen, es ist das Genialste, was jemals auf unserem Planeten passiert ist: ein eigener Planet in einem Menschen; und dennoch egal, jetzt geht es eigentlich wieder um den Planeten Erde; MHTS phantasy game in my head -- es ist so krass genial gewesen mit mir zu spielen!!!!])



ALSO PLANET ERDE:

Ni donas, hm? -- Wir geben, schenken, aha... es ist nicht so leicht...

Was ist erlaubt zu geben?

VS.

Was KANN man geben? (Readme.org: wirklich eine Errungenschaft der Menschheit, oder?!)


@M nochmal: überhaupt, dass jmd. so ein Kind pflegen muss, dass eine Mutter ihr Kind so misshandeln kann, dass es ein Pflegefall wird: genau sowas kann alles VERUNMÖGLICHT werden durch diese Schriften, diesen Ansatz, diesen fortwährenden Plan. Wirklich darum geht's hier: dass die Menschen ihre sozialen Beziehungen möglichst konstruktiv leben können... Gesundheit und soziale Vernunft... ja super auf einmal ist es da...

Eine Alternative: so verdammt gefährlich, ja!
